# Generated by Django 6.0 on 2026-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField(blank=True, help_text='Zadejte váhu v kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='Zadejte výšku v cm', null=True)),
            ],
        ),
    ]
