# Generated by Django 6.0 on 2026-01-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_baby_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='height',
            field=models.FloatField(blank=True, help_text='Zadejte výšku v cm při narození', null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='weight',
            field=models.FloatField(blank=True, help_text='Zadejte váhu v kg při narození', null=True),
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(help_text='Zadejte váhu v kg při')),
                ('height', models.FloatField(help_text='Zadejte výšku v cm při')),
                ('note', models.TextField(blank=True, max_length=200)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.baby')),
            ],
        ),
    ]
